### ISSUE TITLE
XHAIL error

### ISSUE THREAD

**Issue by mishalkazmi** [stefano-bragaglia/XHAIL#1]
Dear Stefano,

I am writing to you in regards to XHAIL installation. From the README file available I follow all the instructions and I am able to run the examples you have provided using XHAIL on two different computers. I made sure the environment and the gringo and clasp versions were identical as well on both of them, however when I run it with my own xhail.lp file then for one of my computers it works and on the other system it gives me the following error:

```
*** ERROR (xhail): expected ATOM but EOF found
```

I would really appreciate it if you could get back to me.
- Mishal

**Comment by stefano-bragaglia** [comment]
Hi Mishal,

```
thanks for your mail!
```

With the little information provided, it’s a little bit difficult to understand where the problem lies…

Are both your machines running the same operating system? If so, it might be that Clasp/Gringo versions for those operating systems behave in a slightly different way…

If this is not the case, it might be that you don’t have rights to write on the temp folder of that machine or you don’t have enough free space…

Let me know if any of the above solves your problem; if not, we will look for other options!

Regards,
     Stefano

**Comment by mishalkazmi** [comment]
Hi Stefano,

Thanks for the quick response.

Both of my systems are Linux. I have the same Java versions 1.8.0_74 on
them. They both have Gringo (3.0.5) and Clasp (3.1.0) and Gradle (2.11).
Space is not an issue on the computer either.
I have also attached the .lp file I am using.
It is just strange with everything exactly the same and for both of them to
work on the example sets provided by you; it only works on one of my
systems and not on the other.

Best,

Mishal Kazmi
PhD Student in Electronics Engineering
Human Language and Speech Technologies Lab
Sabanci University

**Comment by stefano-bragaglia** [comment]
Mishal,

```
mmm, this is very strange!
```

I still have the feeling that it is a matter of software configuration… 
Anyway, can you please run your problem with the -d (or —debug) option?
You’ll find temporary gringo/clasp files in a subfolder of the directory where you run XHAIL…
Can you check of these files look the same and if the ASP problems that they contain are meaningful?

Stefano

PS: github blocks attachments, please post your problem in the body of the message, thanks!

**Comment by mishalkazmi** [comment]
Ah yes I think that is the issue. These tmp gringo/clasp files are created
but I cannot view them once xhail is finished running.
For example: After running with debug I get the following:

```
*** Info  (xhail): calling
'/home/mishal/gringo-3.0.5-source/build/release/bin/gringo
/tmp/xhail2887126855371144760.tmp'
*** Info  (xhail): calling
'/home/mishal/clasp-3.1.0/build/release/bin/clasp
/tmp/xhail7598446082848691343.tmp --verbose=0 --opt-mode=optN'
*** ERROR (xhail): expected ATOM but EOF found
```

And these tmp files can't be found. In the temp folder I just have the .lp
file obtained after abduction.

Best,

Mishal Kazmi
PhD Student in Electronics Engineering
Human Language and Speech Technologies Lab
Sabanci University

**Comment by stefano-bragaglia** [comment]
It seems that, for some reason, your user account cannot write in that folder…
Is it your /home folder? Do you have the rights (check with chmod)? Does chown solves something (to be used with care)?
Anyway it’s matter of the configuration of your Linux machine, and not XHAIL...

Let me know if I can further help!

Stefano

PS: You can contact my former supervisor Oliver Ray at the University of Bristol (https://www.cs.bris.ac.uk/~oray/)… I heard that they are bringing on the development!

**Comment by mishalkazmi** [comment]
Thanks Stefano!

Mishal Kazmi
PhD Student in Electronics Engineering
Human Language and Speech Technologies Lab
Sabanci University

On Tue, Jul 26, 2016 at 1:32 PM, Stefano Bragaglia <notifications@github.com
